name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM Version
        run: npm i -g npm
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Lib Dependencies
        run: npm i
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Run tests
        run: npm test
        if: ${{ steps.release.outputs.release_created }}

      - name: Run Publint
        run: npx publint
        if: ${{ steps.release.outputs.release_created }}

# Comment out the NPM publish workflow until we set it up
#      - name: NPM Publish
#        run: npm publish --provenance --access public
#        if: ${{ steps.release.outputs.release_created }}
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
